[2023-10-30T01:16:57.081+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task manual__2023-10-30T01:14:55.133817+00:00 [queued]>
[2023-10-30T01:16:57.094+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task manual__2023-10-30T01:14:55.133817+00:00 [queued]>
[2023-10-30T01:16:57.096+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 5
[2023-10-30T01:16:57.118+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): asteroides-etl-task> on 2023-10-30 01:14:55.133817+00:00
[2023-10-30T01:16:57.126+0000] {standard_task_runner.py:57} INFO - Started process 2116 to run task
[2023-10-30T01:16:57.131+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'asteroides-etl-dag', 'asteroides-etl-task', 'manual__2023-10-30T01:14:55.133817+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/asteroides-etl_dag.py', '--cfg-path', '/tmp/tmpfku2c04n']
[2023-10-30T01:16:57.133+0000] {standard_task_runner.py:85} INFO - Job 161: Subtask asteroides-etl-task
[2023-10-30T01:16:57.206+0000] {task_command.py:416} INFO - Running <TaskInstance: asteroides-etl-dag.asteroides-etl-task manual__2023-10-30T01:14:55.133817+00:00 [running]> on host ac9f9bef16c9
[2023-10-30T01:16:57.341+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Norman Ruiz' AIRFLOW_CTX_DAG_ID='asteroides-etl-dag' AIRFLOW_CTX_TASK_ID='asteroides-etl-task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-30T01:14:55.133817+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-30T01:14:55.133817+00:00'
[2023-10-30T01:16:57.343+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-30T01:16:57.345+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec asteroides-etl /usr/bin/python3 /opt/asteorides-etl/app.py']
[2023-10-30T01:16:57.368+0000] {subprocess.py:86} INFO - Output:
[2023-10-30T01:16:57.401+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2023-10-30T01:16:57.403+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-30T01:16:57.420+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-30T01:16:57.425+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=asteroides-etl-dag, task_id=asteroides-etl-task, execution_date=20231030T011455, start_date=20231030T011657, end_date=20231030T011657
[2023-10-30T01:16:57.443+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 161 for task asteroides-etl-task (Bash command failed. The command returned a non-zero exit code 1.; 2116)
[2023-10-30T01:16:57.466+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-30T01:16:57.492+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
