[2023-10-30T15:29:34.189+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task scheduled__2023-07-20T00:00:00+00:00 [queued]>
[2023-10-30T15:29:34.209+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task scheduled__2023-07-20T00:00:00+00:00 [queued]>
[2023-10-30T15:29:34.209+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 5
[2023-10-30T15:29:34.237+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): asteroides-etl-task> on 2023-07-20 00:00:00+00:00
[2023-10-30T15:29:34.246+0000] {standard_task_runner.py:57} INFO - Started process 3397 to run task
[2023-10-30T15:29:34.252+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'asteroides-etl-dag', 'asteroides-etl-task', 'scheduled__2023-07-20T00:00:00+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/asteroides-etl_dag.py', '--cfg-path', '/tmp/tmpqg6ds_26']
[2023-10-30T15:29:34.253+0000] {standard_task_runner.py:85} INFO - Job 262: Subtask asteroides-etl-task
[2023-10-30T15:29:34.331+0000] {task_command.py:416} INFO - Running <TaskInstance: asteroides-etl-dag.asteroides-etl-task scheduled__2023-07-20T00:00:00+00:00 [running]> on host d87e86d3d093
[2023-10-30T15:29:34.451+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Norman Ruiz' AIRFLOW_CTX_DAG_ID='asteroides-etl-dag' AIRFLOW_CTX_TASK_ID='asteroides-etl-task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-20T00:00:00+00:00'
[2023-10-30T15:29:34.453+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-30T15:29:34.454+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker run -i asteroides-etl']
[2023-10-30T15:29:34.478+0000] {subprocess.py:86} INFO - Output:
[2023-10-30T15:29:34.518+0000] {subprocess.py:93} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2023-10-30T15:29:34.519+0000] {subprocess.py:93} INFO - See 'docker run --help'.
[2023-10-30T15:29:34.521+0000] {subprocess.py:97} INFO - Command exited with return code 125
[2023-10-30T15:29:34.543+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2023-10-30T15:29:34.549+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=asteroides-etl-dag, task_id=asteroides-etl-task, execution_date=20230720T000000, start_date=20231030T152934, end_date=20231030T152934
[2023-10-30T15:29:34.588+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 262 for task asteroides-etl-task (Bash command failed. The command returned a non-zero exit code 125.; 3397)
[2023-10-30T15:29:34.630+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-30T15:29:34.687+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
