[2023-10-30T15:29:35.290+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task scheduled__2023-07-26T00:00:00+00:00 [queued]>
[2023-10-30T15:29:35.315+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task scheduled__2023-07-26T00:00:00+00:00 [queued]>
[2023-10-30T15:29:35.316+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 5
[2023-10-30T15:29:35.351+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): asteroides-etl-task> on 2023-07-26 00:00:00+00:00
[2023-10-30T15:29:35.363+0000] {standard_task_runner.py:57} INFO - Started process 3442 to run task
[2023-10-30T15:29:35.369+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'asteroides-etl-dag', 'asteroides-etl-task', 'scheduled__2023-07-26T00:00:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/asteroides-etl_dag.py', '--cfg-path', '/tmp/tmpsu3t0cmb']
[2023-10-30T15:29:35.373+0000] {standard_task_runner.py:85} INFO - Job 267: Subtask asteroides-etl-task
[2023-10-30T15:29:35.455+0000] {task_command.py:416} INFO - Running <TaskInstance: asteroides-etl-dag.asteroides-etl-task scheduled__2023-07-26T00:00:00+00:00 [running]> on host d87e86d3d093
[2023-10-30T15:29:35.586+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Norman Ruiz' AIRFLOW_CTX_DAG_ID='asteroides-etl-dag' AIRFLOW_CTX_TASK_ID='asteroides-etl-task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-26T00:00:00+00:00'
[2023-10-30T15:29:35.588+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-30T15:29:35.589+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker run -i asteroides-etl']
[2023-10-30T15:29:35.618+0000] {subprocess.py:86} INFO - Output:
[2023-10-30T15:29:35.662+0000] {subprocess.py:93} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2023-10-30T15:29:35.663+0000] {subprocess.py:93} INFO - See 'docker run --help'.
[2023-10-30T15:29:35.666+0000] {subprocess.py:97} INFO - Command exited with return code 125
[2023-10-30T15:29:35.686+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2023-10-30T15:29:35.694+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=asteroides-etl-dag, task_id=asteroides-etl-task, execution_date=20230726T000000, start_date=20231030T152935, end_date=20231030T152935
[2023-10-30T15:29:35.718+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 267 for task asteroides-etl-task (Bash command failed. The command returned a non-zero exit code 125.; 3442)
[2023-10-30T15:29:35.747+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-30T15:29:35.780+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
